### ISSUE TITLE
Checkout step5: add participants/jumpers (for liability waivers)

### ISSUE THREAD

**Issue by prb01** [Scott-Coates-Org/group-project-team-blue#79]
- Ability to add participants/jumpers dynamically
- Ability to remove participants/jumpers
- Ability to enter name of participant/jumper
- Add names to redux store on Continue

![image](https://user-images.githubusercontent.com/45342505/179397441-2e002684-d822-45b7-9023-e38ff63db996.png)

**Comment by giest95** [comment]
Done
