### ISSUE TITLE
Admin/Bookings: datasource is not defined

### ISSUE THREAD

**Issue by prb01** [Scott-Coates-Org/group-project-team-blue#81]
![image](https://user-images.githubusercontent.com/45342505/179397732-9ff0358e-164b-4fc4-a977-71c7be892cfd.png)

![image](https://user-images.githubusercontent.com/45342505/179397751-97fc8a93-f5df-43ee-8ed7-6030bf9f6714.png)

**Comment by giest95** [comment]
All good
